### PR TITLE
Private events

### PR DESCRIPTION
**Pull request by che30**
In this project we implemented the following 
- Created an User model with its association validations controllers and views
- Created a sessions controller ,views and routes to log in and authenticate users
-  Created an Event model with its association validations controllers and views
- Created an Attendance model with its association validations controllers and views
- Added an attendance form for users to attend events 
- Added links to move between different views
- Added rspecs  test model,feature,views and authentication  
- 
This project was reviewed by the first 3 TSE and you can see a screenshot of one of them giving the executable results while it is running fine with success. How do u guys expect me to fix a problem at your end that am not fully informed about? This code runs fine for me here but any if u keep getting the same error. I don't know what you guys expect me to do to solve a problem at your end am not fully informed of. A friend cloned this project and he was facing the same error and he used `yarn install -check-files` and it worked for him . It already worked for the first 3 TSE how do you guys expect me to make it work at your end when am trying to connect with you guys after the review on slack to fully understand the problem and solve but none of you guys have been availaible 
# checkout how to install  webpacker on the readme it will solve the problem.

### CODE REVIEW

**Review by Georjane — CHANGES_REQUESTED** [review]
Implemented most changes  as required  but still have rubocop failing

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Leonardo Castillo Riaño& Blanco Blanchard** 
Good job with the improvements for this project :muscle:  :muscle: 
There are some issues to solve before you can go ahead:

- [x] Fix rubocop offenses
- [x] Add a screenshot in your README file
- [x] Don't overuse rubocop disable
- [x] Remove commented code in UsersController
- [x] In the README file, "Author 2" name is listed two times
- [ ] User's show page should only show the events created by the user and the events where the user is an attendee (separated by previous and upcoming)
- [x] One of your test is failing

 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Comment by che30** [comment]
Fixed all the changes except one I did not understand what the TSE meant and he was no where to be found

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Leonardo Castillo Riaño [status: Enrolled] & Blanco Blanchard** 
Nice job with the improvements :muscle:  :muscle:
Your are almost there :clap: :clap: :clap:  
Just one last details to improve:
- [x] This is the expected behavior that I have to check on user's show


In the test I did, user "b" attended only one event ("a event 2" from user "a"), but the "user show" page shows all the previous and upcoming events (even those the user is not attending):


 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Comment by che30** [comment]
Am afraid the change requested is not part of odin project

**Review by teekaytech — CHANGES_REQUESTED** [review]
-Added logic for user upcoming event and past events as required

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Changes Required :recycle: 
### Hello :wave: 
##### There was an error when I started the local server and tried to visit the project on the browser. Find below the screenshot of the error I got.
Screenshot from 2021-01-08 23-39-57
### Please fix the error and request another review.
slack(@ebeagusamuel)

**Comment by che30** [comment]
I have no problem with this code locally the problem must be at your end however my partner used to face that problem when we were working each time he pulled and we corrected by installing webpacker

**Review by mcrd25 — CHANGES_REQUESTED** [review]
This project was reviewed by the first 3 TSE and you can see a screenshot of one of them giving the executable results while it is running fine with success. How do u guys expect me to fix a problem at your end that am not fully informed about? This code runs fine for me here but any if u keep getting the same error 
# checkout how to install  webpacker on the readme it will solve the problem

**Review by javitocor — CHANGES_REQUESTED** [review]
# STATUS CHANGES REQUIRED ♻️ 

Hello team! 👋 
A great effort in this project 👍 
However, we still to implement some changes in order to get it approved 💪 
Kindly check my comments below 👇  apply the changes and resubmit your project for a new code review ⏩ 
Good luck! 😺 
## Mandatory changes
- In your readme file, try to be more specific with the instructions to run your project, I guess the user should run db:migate...
- The order of the sections should be Getting started and inside that section, prerequisites and then set up and then usage. Do not write twice the instructions
- Add an acknowledgement section, we always should be thanksful
- Following the instructions on your readme file, I keep having the same error. Kindly fix it

**Review by teekaytech — APPROVED** [review]
# Status: Approved :green_circle: 

### Congratulations team, this project has passed all the mandatory requirements. It is therefore approved :heavy_check_mark:

Again, congratulations, you can merge to master.
Good luck with your next task.

* * * 
**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Pull request merged**
